database:
  name: sampledb
  user: "my-user"
  password: "my-password"
eap8:
  # This configuration file can be used to build and deploy the todo-backend
  # quickstart on OpenShift with the Helm Chart for EAP.
  build:
    uri: https://github.com/jboss-developer/jboss-eap-quickstarts.git
    ref: 8.0.x
    contextDir: todo-backend
    env:
      - name: POSTGRESQL_DRIVER_VERSION
        value: '42.6.0'
  deploy:
    replicas: 1
    env:
      # Env vars to connect to PostgreSQL DB
      - name: POSTGRESQL_DATABASE
        valueFrom:
          secretKeyRef:
            key: database-name
            name: postgresql
      - name: POSTGRESQL_USER
        valueFrom:
          secretKeyRef:
            key: database-user
            name: postgresql
      - name: POSTGRESQL_PASSWORD
        valueFrom:
          secretKeyRef:
            key: database-password
            name: postgresql
      - name: POSTGRESQL_DATASOURCE
        value: ToDos
      - name: POSTGRESQL_SERVICE_HOST
        value: postgresql
